name: "WIPLog"
description: "it's a pun on weep log, get it?"
meta_description: "Blog about anime and programming languages"

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
baseurl: ""
domain_name: ""
google_analytics: "UA-XXXXXXXX-X"
plugins: [jekyll-paginate]

# Details for the RSS feed generator
url: ""
author: "Shubham Kumar"

# Disqus config
disqus-shortname: ""
